spring.cloud.stream:
  function:
    definition: orderProcessor
  bindings:
    orderProcessor-in-0:
      destination: order.push
    orderProcessor-out-0:
      destination: order.active.push
  kafka:
    bindings:
      orderProcessor-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      orderProcessor-out-0:
        producer:
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
    binder:
      brokers:
        - localhost:9091
        - localhost:9092